### ISSUE TITLE
_BSD_SOURCE deprecated in glibc >= 2.20

### ISSUE THREAD

**Issue by einhov** [mikeryan/ems-flasher#12]
Building with -Werror fails when building against glibc >= 2.20 due to a deprecated macro. According to `man 7 feature_test_macros`, the macro `_DEFAULT_SOURCE` should be defined in addition to `_BSD_SOURCE` to get around this warning.

**Comment by chastai** [comment]
Thanks for your report.
I've replaced _BSD_SOURCE by _XOPEN_SOURCE 500 instead to be consistent with the rest of the program and as that works too for usleep().
However I was unable to reproduce the problem (with Ubuntu 16.04, glibc 2.23).
Which system have you used?
Here is the branch wtith the changes : https://github.com/mikeryan/ems-flasher/tree/fix-12

**Comment by einhov** [comment]
With the changes in that branch, the program builds without issue on ArchLinux
with glibc 2.23.

The warning appears to be [patched out](http://packages.ubuntu.com/xenial/all/glibc-source/filelist) in Ubuntu:
/usr/src/glibc/debian/patches/ubuntu/local-warn-bsd-source.diff

**Comment by chastai** [comment]
Merged. Thank you.
