### ISSUE TITLE
Menu/game not loaded after transferring

### ISSUE THREAD

**Issue by dannye** [mikeryan/ems-flasher#14]
First off, I wanted to say thank you for making this! I've been struggling for weeks with the Windows drivers with no luck, so I'm glad this alternative exists for Mac.

My issue is that after I copy a rom to the flash cart, and then put the flash cart in a real Gameboy or a real Super Gameboy, the screen is only blank after the first flashing "Gameboy" logo.

I wonder if the problem is with menus.gb.

Here is my terminal output:

```
Daniels-MacBook-Pro-2:ems-flasher Daniel$ ./ems-flasher --format --verbose
trying to find EMS cart
claimed EMS cart
base address is 0x0
Formating...
Daniels-MacBook-Pro-2:ems-flasher Daniel$ ./ems-flasher --title --verbose
trying to find EMS cart
claimed EMS cart
base address is 0x0
Bank  Title             Size     Enhancements

Page: 1
Menu: no menu ROM found at bank 0
Free space: 4096 KB
Daniels-MacBook-Pro-2:ems-flasher Daniel$ ./ems-flasher --write pokered.gb --verbose
trying to find EMS cart
claimed EMS cart
base address is 0x0
Loading the menu ROM...Writing /usr/local/share/ems-flasher/menus.gb [MENU#]...
   3% 01:06
Writing pokered.gb [POKEMON RED]...
 100% 00:00
Daniels-MacBook-Pro-2:ems-flasher Daniel$ ./ems-flasher --title --verbose
trying to find EMS cart
claimed EMS cart
base address is 0x0
Bank  Title             Size     Enhancements
  0   MENU#               32 KB  SGB
 64   POKEMON RED       1024 KB  SGB

Page: 1
Page enhancements: SGB
Compatible consoles: All
Free space: 3040 KB
```

It looks like when writing the menu rom, it stops at 3% before moving on to writing the game rom. Do you have any suggestions?

Thanks for reading.

**Comment by dannye** [comment]
Actually, it looks like the 3% thing is a simple output error, since 32 KB is 3% of 1024 KB
So after all 32 KB of the menu rom is written, it mistakenly reports that it is 3% complete.

Regardless, I'm still having the issue of nothing appearing on my Gameboy screen.

**Comment by chastai** [comment]
Hello,

Thanks for you report.

The 3% thing is in fact the expected behavior, I have bad tastes I know :-p but that could easily be changed ;-)

Maybe your problem is related to issue #9 solved with PR #11.
Have you updated your repo to the last revision?

Then recompile the project:
```
make clean
./config.sh --dev # dev release: executable will use menus.gb in current dir
make menu-orig # this should regenerate menus.gb from a precompiled menu
make
```
Christophe.

**Comment by dannye** [comment]
Thank you for the reply.

My repo is up to date. I used `--dev` and remade the menu roms, but I had the same behavior as before on the Gameboy after transferring.

Shortly after making this issue report, I found a fork of this project belonging to a friend of mine, and it worked just fine for me:
https://github.com/Drenn1/ems-flasher

**Comment by chastai** [comment]
Note that Drenn1 version is buggy as erase-blocks are never erased before rewrite (I've opened an issue about that). It should be fine if you never remove ROMs though.

I've attached compiled menus. menus.gb worked for me on a Game Boy Color. Please compare menus.gb with your version before replacing it and then try again if the files were different. [menuorig.tar.gz](https://github.com/mikeryan/ems-flasher/files/376520/menuorig.tar.gz)

You could also check if the menu have been correctly flashed:
```
./ems-flasher --read tmp.gb # wait say 5sec, we only need the first 32K
dd if=tmp.gb of=tmp2.gb bs=32K count=1 # truncate the file
cmp tmp2.gb menus.gb # no news is good news
```
Christophe.

**Comment by dannye** [comment]
The menu file read from the cart was the same as the one you provided.

**Comment by chastai** [comment]
Ah, it must be the menu itself so. I will look at it when I have time.

**Comment by tuanhtrng** [comment]
I experience the same issue as OP. However, the menu loads fine when I attempted to write 2 gbc files at once. I will try different combinations and report to you later.

**Comment by chastai** [comment]
Fixed in master. This was a bug in the menu. Checkout master and do a make to rebuild the menu variants.

Thanks for you reports and sorry for the delay.

**Comment by dannye** [comment]
Thank you so much for helping out! I'll try this out and let you know if I have any other problems.

**Comment by chastai** [comment]
It's a pleasure! I have more time for me at the moment, so there are chances that I solve other issues more quickly ;-)
