### ISSUE TITLE
GBC ROM flashing leads to logo lockup(Nintend-)

### ISSUE THREAD

**Issue by SjorsVanGelderen** [mikeryan/ems-flasher#16]
It seems that whenever I try to flash any GBC ROM the cartridge is unable to start either on a Game Boy Light or a Game Boy Color.
The Nintendo logo is incomplete and locks.
This happens with all GBC ROMs I've tested so far.
I think it may be related to the menu ROM for GBCs.
I don't have this issue when there are only GB ROMs on the cartridge.
Flashing seems to be successful, no error messages even with the `--verbose` option.

**Comment by chastai** [comment]
I don't experiment this issue. Have you tried the latest version? as it contains a fix to the menu to issue #14 that is may be related to your problem. Don't forget to type `make` to update  all variants of the menu with the fix.

**Comment by SjorsVanGelderen** [comment]
I've cloned the repository anew, installed according to the instructions, but the issue remains.
Different GBC ROMs from different sources were tried. None actually work.
I've also confirmed that regular GB ROMs work properly even with the Game Boy Color as is to be expected.

**Comment by chastai** [comment]
You can test the dump with [BGB](http://bgb.bircd.org/). This emulator emulates the EMS card but you'll need to set the title to 'GB16M': `rgbfix -v -tGB16M image.gb` (rgbfix is part of [RGBDS](https://github.com/bentley/rgbds)).

Also, what you could try:

Delete all ROMS with the exception of the GBC menu and see if the menu is launching.

Flash a GBC ROM directly without a menu. You'll have to compile a older version of ems-flasher, without multi-ROM support (commit d90fa3f).

After that, we will have to determine where the problem occurs by modifying the menu

**Comment by SjorsVanGelderen** [comment]
Actually some ROMs seem to be working correctly. I will reopen the issue if I can find the source of the problem.
