### ISSUE TITLE
Invalid header for menus.gb on write

### ISSUE THREAD

**Issue by cdl** [mikeryan/ems-flasher#9]
Hey there,

Trying to write to my cart is giving me the following error every time I try to write a ROM (`./ems-flasher --verbose --write lsdj.gb`):

```
trying to find EMS cart
claimed EMS cart
base address is 0x0
ems-flasher: invalid header for /usr/local/share/ems-flasher/menus.gb
```

I went ahead and moved the cloned repo to `/usr/local/share/` to solve a previous issue where it couldn't find `menus.gb` (project root apparently needs to be `/user/local/share/ems-flasher/`), however, I can't seem to get past this issue.

Deleting and formatting from the cart works totally fine, albeit needing to unplug/plug back in the cart after every action (otherwise the program can't seem to find the cart). I'm on OS X, with the latest build dependencies. The compile (`make`) seemed to run just fine.

Let me know if you need any more info from me for debugging!

**Comment by cdl** [comment]
Decided to try recompiling from source on an Ubuntu 15.10 VM (`libusb` and `pkg-config` both installed). Looks like the `check-menu` step fails, and using the precompiled menu.gb doesn't appear to work.

Got it to work eventually by setting up `rgbds` so I could compile the menu from source with `make menu`.

Below is the output I get when trying to run `make menu-orig`, and the failing `check-menu` log.

```
colby@colby-VirtualBox:~/Desktop/ems-flasher$ make menu-orig
cp menu.gb.orig menu.gb
make check-menu
make[1]: Entering directory '/home/colby/Desktop/ems-flasher'
./updateheader.sh -c -s  < menu.gb > menucs.gb
./updateheader.sh: 19: ./updateheader.sh: [[: not found
./updateheader.sh: 25: ./updateheader.sh: [[: not found
./updateheader.sh -c < menu.gb > menuc.gb
./updateheader.sh: 19: ./updateheader.sh: [[: not found
./updateheader.sh: 25: ./updateheader.sh: [[: not found
./updateheader.sh -s < menu.gb > menus.gb
./updateheader.sh: 19: ./updateheader.sh: [[: not found
./updateheader.sh: 25: ./updateheader.sh: [[: not found
make[1]: Leaving directory '/home/colby/Desktop/ems-flasher'
```

**Comment by hswick** [comment]
Also having similar issue, but mine says invalid header for menu.c
```
ems-flasher: invalid header for /usr/local/share/ems-flasher/menuc.gb
```
Did you ever get this to work on OSX @cdl?

**Comment by chastai** [comment]
Hi,

I've fixed the issue you have experimented under Ubuntu. See PR #10 .

Please apply the commit in PR #10 and try this to test ems-flasher without installing it :

```
make clean-all # this will also remove the menu ROMs in the build dir
make menu-orig # reconstitute the menu ROMs from a precompiled one.
make ems-flasher-dev # the executable will expect the menu ROMs to be in the current dir.
```
And to install it under /usr/local if you want:
```
rm cmd.o # as the menu directory is hardcoded
make ems-flasher
make install # as root
```
I have yet to improve the Makefile and probably write a configuration script and documentation.

You shouldn't need to unplug and replug the cart after every action. I will investigate that.
Could you check if libusb_release_interface() is well called in ems_deinit() when the process exits?
ems_deinit() is registered with atexit().

Christophe.

**Comment by endrift** [comment]
The OS X issue is caused by gawk running in the wrong locale, emitting mojibake.

    diff --git a/updateheader.sh b/updateheader.sh
    index 05f2535..aa96867 100755
    --- a/updateheader.sh
    +++ b/updateheader.sh
    @@ -26,7 +26,7 @@ if [[ $? == 0 ]]; then
         OD="god"
     fi
     
    -$OD -v -Ad -tu1 -w1 | $AWK -vcolor=$color -vsuper=$super '
    +$OD -v -Ad -tu1 -w1 | LC_ALL=C $AWK -vcolor=$color -vsuper=$super '
     BEGIN {
         split( \
             " 206 237 102 102 204  13   0  11   3 115   0 131   0  12   0  13" \

I'll file a PR tonight.

**Comment by zeroeth** [comment]
For anyone else coming across this be sure to install the GNU coreutils for OSX as the flags are different.

    brew install coreutils

After that worked a treat!
